name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Inject env vars
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build
